name: Unit tests

on: [push, pull_request]

jobs:
  ubuntu:
    strategy:
      matrix:
        python: [3.10, 3.11, 3.12]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          poetry run pip install matplotlib
      - name: pytest
        run: |
          poetry run pytest
